darkChoco/urls.py
from django.urls import path
from . import views

app_name = 'darkChoco'

urlpatterns = [
    path('post/', views.post, name='post'),
    path('jsPost/', views.JsCreatePostView.as_view(), name='jsPost'),
]

sweetProject/urls.py
from django.contrib import admin
from django.urls import path, include
import darkChoco.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', darkChoco.views.index, name='index'),
    path('darkChoco/', include('darkChoco.urls')),
    path('whiteChoco/', include('whiteChoco.urls')),
]

whiteChoco/urls.py
from django.urls import path
from . import views

app_name = 'whiteChoco'

urlpatterns = [
    path('signup/', views.CreateUserView.as_view(), name='signup'),
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
    path('userpage/<str:nickname>', views.userpage, name='userpage'),
    path('jsSignup/', views.JsCreateUserView.as_view(), name='jsSignup'),
]

whiteChoco/models.py
from operator import mod
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=10)

    def __str__(self):
        return self.nickname

whiteChoco/views.py
from django.contrib.auth.models import User
from django.contrib.auth.views import LogoutView
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib import auth, messages
from django.views import View
from whiteChoco.models import Profile
from darkChoco.models import Letter
from django.http import JsonResponse
import json

class CreateUserView(View):
    def get(self, request):
        return render(request, 'signup.html')

    def post(self, request):
        if request.POST["password1"] == request.POST["password2"]:
            user = User.objects.create_user(
                    username=request.POST["username"],
                    email=request.POST["username"],
                    password=request.POST["password1"]
                )
            nickname = request.POST["nickname"]
            profile = Profile(user=user, nickname=nickname)
            profile.save()
            auth.login(request,user)
            return redirect('whiteChoco:userpage', nickname=nickname)

class LoginUserView(View):
    def get(self, request):
        return render(request, 'login.html')

    def post(self, request):
        username = request.POST["username"]
        password = request.POST["password"]
        user = auth.authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user)
            profileModel = Profile.objects.get(user=user)
            return redirect('whiteChoco:userpage', nickname=profileModel.nickname)
        else:
            messages.info(request, '아이디, 패스워드를 확인하세요')
            return redirect('index')

class LogoutViews(LogoutView):
    next_page = 'index'
logout = LogoutViews.as_view()

def userpage(request, nickname):
    try:
        profileModel = Profile.objects.get(nickname=nickname)
        letters = Letter.objects.filter(to_user=nickname).order_by('-send_date')
        context = {
            'nickname' : profileModel.nickname,
            'letters' : letters,
        }
        return render(request, 'userpage.html', context=context)
    except:
        messages.info(request, '사용자 없음!')
        return redirect('index')

############### JSON ###############
class JsCreateUserView(View):
    def get(self, request):
        return render(request, 'singup.html')

    def post(self, request):
        response = {}
        
        body = request.body.decode('utf8')
        data = json.loads(body)

        if User.objects.filter(username=data['username']): 
            response["result"] = "false"
            response["error_code"] = "201"
            response["message"] = "이미 사용중인 아이디 입니다."
            response["return_url"] = "/"
            return JsonResponse(response, json_dumps_params = {'ensure_ascii': False})
        else:
            if data['password1'] == data['password1']: # 비밀번호 1과 2 비교
                try:
                    if Profile.objects.filter(nickname=data['nickname']):
                        response["result"] = "false"
                        response["error_code"] = "202"
                        response["message"] = "이미 사용중인 닉네임 입니다."
                        response["return_url"] = "/"
                        return JsonResponse(response, json_dumps_params = {'ensure_ascii': False})
                    else:
                        user = User.objects.create_user(
                                username=request.POST["username"],
                                email=request.POST["username"],
                                password=request.POST["password1"]
                            )
                        nickname = request.POST["nickname"]
                        profile = Profile(user=user, nickname=nickname)
                        profile.save()
                        auth.login(request,user)
                        return redirect('whiteChoco:userpage', nickname=nickname)
                except KeyError:
                    response["result"] = "false"
                    response["error_code"] = "203"
                    response["message"] = "회원가입에 실패하였습니다."
                    response["return_url"] = "/"
            else :
                response["result"] = "false"
                response["error_code"] = "204"
                response["message"] = "비밀번호가 서로 다릅니다."
                response["return_url"] = "/"
            return JsonResponse(response, json_dumps_params = {'ensure_ascii': False})

whiteChoco/templates/login.html
<form action="{% url 'whiteChoco:login' %}" method="POST">
    {%csrf_token%}
    <p>
        <input type="text" name="username" placeholder="login id">
    </p>
    <p>
        <input type="password" name="password" placeholder="password">
    </p>
    <button type="submit">로그인</button>
</form>
<a href="{% url 'index' %}">Home</a>

whiteChoco/templates/signup.html
<form action="{% url 'whiteChoco:signup'%}" method="POST" >
    {%csrf_token%}
    <p>
        <input type="email" name="username" placeholder="이메일">
    </p>
    <p>
        <input type="text" name="nickname" placeholder="닉네임">
    </p>
    <p>
        <input type="password" name="password1" placeholder="비밀번호">
    </p>
    <p>
        <input type="password" name="password2" placeholder="비밀번호 확인">
    </p>
    <button type="submit">회원가입</button>
</form>
<a href="{% url 'index' %}">첫 화면</a>

whiteChoco/templates/userpage.html
<hr>
<p>로그인한 사용자 정보</p>
<p>ID : {{user.username}}</p>
<p>닉네임 : {{user.profile.nickname}}</p>
<p><a href="{% url 'whiteChoco:logout' %}">로그아웃</a></p>
<hr>
<p>현재 페이지 주인</p>
{{nickname}}
<hr>
<form action="{% url 'darkChoco:post' %}" method="POST">
    <input type="hidden" name="to_user" value="{{nickname}}" />
    <br>
    <textarea cols="40" rows="10" name="letter_text"></textarea>
    <br><br>
    <input type="submit" value="전달!" />
</form>

{% for letter in letters.all %}
    <h1>{{ letter.to_user }}에게</h1>
    <p>{{ letter.letter_text }} - 내용</p>
    <p>{{ letter.from_user }}가</p>
{% endfor %}